
# server properties
server:
  port: 8085

# Secret Key To Generate Token
app:
  secretKey: '[CDE042POD5]'
  jwtValidityMinutes: 15
  
# spring properties
spring:
  application:
    name: AUTH-SERVICE
    
# Configure Database here
  datasource:
    url: jdbc:h2:mem:authentication_db
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
      
# Error Messages
jwtUtil:
  expiredMessage: Token has been expired
  malformedMessage: Token is in invalid format
  signatureMessage: Token signature is invalid
  nullOrEmptyMessage: Token is either null or empty
  unsupportedMessage: Claims for token is not supported
  
userDetails:
  errorMessage: Incorrect Username or Password
  badCredentialsMessage: Incorrect Username or Password
  disabledAccountMessage: Your account has been disabled
  lockedAccountMessage: Your account has been locked, please contact your administrator for more details
  
logging:
 level:
    '[org.springframework.web]': ERROR
    '[com.cts.processPension]': DEBUG       